apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: ob9365nlo-go 
  janus-idp.io/tekton: ob9365nlo-go
  backstage.io/kubernetes-id: ob9365nlo-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ob9365nlo-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml