apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ob9365nlo-go
  janus-idp.io/tekton: ob9365nlo-go
  backstage.io/kubernetes-id: ob9365nlo-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ob9365nlo-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
