apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ob9365nlo-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ob9365nlo-go 
  name: ob9365nlo-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ob9365nlo-go 
